function createfigure2(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 05-Sep-2019 22:35:47

% Create figure
figure;

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Impostor','Marker','diamond','LineWidth',4);

% Create plot
plot(X2,Y2,'DisplayName','Brute Force Attack Genuine','Marker','square',...
    'LineWidth',4,...
    'LineStyle','-.');

% Create plot
plot(X3,Y3,'DisplayName','Brute Force Attack Impostor','MarkerSize',10,...
    'Marker','*',...
    'LineWidth',4);

% Create ylabel
ylabel('Normalised Frequency','FontWeight','bold',...
    'FontName','Times New Roman');

% Create xlabel
xlabel('Normalised Score','FontWeight','bold','FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 0.23]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.35]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',20,'FontWeight','bold',...
    'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.44615814420419 0.76934603556299 0.454107302092547 0.15672074516292],...
    'FontSize',23);

